### ISSUE TITLE
Resources aren't loading

### ISSUE THREAD

**Issue by gjsduarte** [configcat/vscode-extension-configcat#11]
### Describe the bug

The extension crashes when opening a feature flag edit screen.

### To reproduce

Click on a feature flag edit icon. A blank window appears and some errors get logged to the console.

### Expected behavior

A screen to edit the feature flag should appear.

### Screenshots

![image](https://user-images.githubusercontent.com/288812/144045041-41c54f49-f710-4097-b521-25cfe30a9d60.png)

**Comment by laliconfigcat** [comment]
Hello @gjsduarte ,

Thanks for submitting the issue. I just installed the extension from .vsix and from the marketplace too and it works fine for me. Could you please tell me how did you install it? Could you please reinstall the extension to see if that solves the problem?

Cheers,
Lali

**Comment by gjsduarte** [comment]
Hey @laliconfigcat,
I tried installing from the Marketplace and also locally packaging the `vsix` and installing from the current `master`. Same issue on both attempts

**Comment by gjsduarte** [comment]
Just tried cleaning the `~/.vscode/extensions/configcat.configcat-feature-flags-1.1.0/` and reinstalling from the marketplace and had the same issue:
![image](https://user-images.githubusercontent.com/288812/144049487-8f1d5bc1-8411-4668-9ddc-6158c5b37c56.png)

**Comment by laliconfigcat** [comment]
Could you please check the folder if the files are there or not? .vscode\extensions\configcat.configcat-feature-flags-1.1.0\out\dist
runtime.js, polyfills.js, styles.css, main.js

Thanks

**Comment by gjsduarte** [comment]
Yes, all files are there

**Comment by gjsduarte** [comment]
I just asked a colleague to test in his computer, and he had the exact same issue. We're both using MacOS. Could it be related?

**Comment by laliconfigcat** [comment]
Could you please send me the details from the help/about dialog?

**Comment by gjsduarte** [comment]
Sorry, I don't understand what you're asking. Which dialog?

**Comment by laliconfigcat** [comment]
I was asking for the VSCode about dialog to get the version number and other stuff. But in the meantime, one of my colleagues tried it on Mac and it failed for him too (I'm on Win). I am trying to find a fix for it.

**Comment by laliconfigcat** [comment]
I just released v1.1.2 with the fix. Could you please check it?

**Comment by gjsduarte** [comment]
Yup, it seems to work now! Thanks for the quick fix!
